id: IED3FFF3A
ocr_import_info:
  timestamp: '2023-09-27T08:52:31.706222+00:00'
  batch_id: batch-1ef3
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 09:03:22.434292+00:00
last_modified: 2023-09-27 09:03:22.434299+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7922
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7922
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་དགོངས་དོན་བརྗེད་བྱང་།
  languages:
  - bo
  author: གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9201689887339405
  ocr_word_median_confidence_index: 0.99914277
bases:
  I1KG3272:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3272
      total_pages: 508
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3272.txt
    statistics:
      ocr_word_median_confidence_index: 0.99914277
      ocr_word_mean_confidence_index: 0.9201689887339405
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
